FROM FROM_IMAGE
MAINTAINER Nate Coraor <nate@bx.psu.edu>
ENV DEBIAN_FRONTEND noninteractive
VOLUME ["/host"]

RUN apt-get -qq update && \
    apt-get install --no-install-recommends -y make gcc g++ ca-certificates curl zlib1g-dev libssl-dev libbz2-dev python-yaml


COPY buildpy.sh /build/buildpy.sh
WORKDIR /build
RUN bash buildpy.sh

COPY buildpyextras.sh /build/buildpyextras.sh
RUN bash buildpyextras.sh

WORKDIR /

RUN rm -rf /build
RUN apt-get clean
